// Generated by CoffeeScript 1.7.1
(function() {
  this.ArrayMap = (function() {
    var keyify;

    function ArrayMap() {
      this.map = {};
    }

    ArrayMap.prototype.set = function(array, object) {
      if (array instanceof Array) {
        return this.map[keyify(array)] = object;
      } else {
        throw new Error('ArrayMap requires an array-type argument to #set');
      }
    };

    ArrayMap.prototype.get = function(array) {
      if (array instanceof Array) {
        return this.map[keyify(array)];
      } else {
        throw new Error('ArrayMap requires an array-type argument to #get');
      }
    };

    keyify = function(array) {
      return array.join(',');
    };

    return ArrayMap;

  })();

}).call(this);
