// Generated by CoffeeScript 1.7.1
(function() {
  var Tile, asArray, darken,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tile = (function() {
    Tile.prototype.fcolor = '#fff';

    Tile.prototype.bcolor = '#000';

    Tile.prototype.symbol = '?';

    function Tile(x, y) {
      this.x = x;
      this.y = y;
    }

    Tile.prototype.draw = function(display, inFOV) {
      if (inFOV == null) {
        inFOV = false;
      }
      if (inFOV) {
        return display.draw(this.x, this.y, this.symbol, this.fcolor, this.bcolor);
      } else {
        return display.draw(this.x, this.y, this.symbol, darken(this.fcolor, 0.8), darken(this.bcolor, 0.8));
      }
    };

    return Tile;

  })();

  this.Floor = (function(_super) {
    __extends(Floor, _super);

    Floor.prototype.symbol = '.';

    function Floor(x, y) {
      this.x = x;
      this.y = y;
      this.fcolor = darken('#ddd', ROT.RNG.getUniform() * 0.2);
      this.bcolor = darken('#111', ROT.RNG.getUniform() * 0.2);
    }

    return Floor;

  })(Tile);

  this.Wall = (function(_super) {
    __extends(Wall, _super);

    Wall.prototype.symbol = '#';

    function Wall(x, y) {
      this.x = x;
      this.y = y;
      this.fcolor = darken('#222', ROT.RNG.getUniform() * 0.2);
      this.bcolor = darken('#bbb', ROT.RNG.getUniform() * 0.4);
    }

    return Wall;

  })(Tile);

  asArray = function(hex, callback) {
    var a;
    a = ROT.Color.fromString(hex);
    return ROT.Color.toHex(callback(a));
  };

  darken = function(color, amount) {
    return asArray(color, function(a) {
      return ROT.Color.interpolate(a, [0, 0, 0], amount);
    });
  };

}).call(this);
