// Generated by CoffeeScript 1.7.1
(function() {
  var Tile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tile = (function() {
    function Tile(x, y) {
      this.x = x;
      this.y = y;
    }

    Tile.prototype.draw = function(display) {
      return display.draw(x, y, '?');
    };

    return Tile;

  })();

  this.Floor = (function(_super) {
    __extends(Floor, _super);

    function Floor() {
      return Floor.__super__.constructor.apply(this, arguments);
    }

    Floor.prototype.draw = function(display, inFOV) {
      if (inFOV) {
        return display.draw(this.x, this.y, '.', '#fff', '#000');
      } else {
        return display.draw(this.x, this.y, '.', '#777', '#222');
      }
    };

    return Floor;

  })(Tile);

  this.Wall = (function(_super) {
    __extends(Wall, _super);

    function Wall() {
      return Wall.__super__.constructor.apply(this, arguments);
    }

    Wall.prototype.draw = function(display, inFOV) {
      if (inFOV == null) {
        inFOV = false;
      }
      if (inFOV) {
        return display.draw(this.x, this.y, '#', '#fff', '#000');
      } else {
        return display.draw(this.x, this.y, '#', '#777', '#222');
      }
    };

    return Wall;

  })(Tile);

}).call(this);
