// Generated by CoffeeScript 1.7.1
(function() {
  var Tile, darken,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tile = (function() {
    Tile.prototype.fcolor = '#fff';

    Tile.prototype.bcolor = '#000';

    Tile.prototype.symbol = '?';

    function Tile(x, y) {
      this.x = x;
      this.y = y;
    }

    Tile.prototype.draw = function(display, inFOV) {
      if (inFOV == null) {
        inFOV = false;
      }
      if (inFOV) {
        return display.draw(this.x, this.y, this.symbol, this.fcolor, this.bcolor);
      } else {
        return display.draw(this.x, this.y, this.symbol, darken(this.fcolor, 0.8), darken(this.bcolor, 0.8));
      }
    };

    return Tile;

  })();

  this.Floor = (function(_super) {
    __extends(Floor, _super);

    function Floor() {
      return Floor.__super__.constructor.apply(this, arguments);
    }

    Floor.prototype.fcolor = '#ddd';

    Floor.prototype.bcolor = '#111';

    Floor.prototype.symbol = '.';

    return Floor;

  })(Tile);

  this.Wall = (function(_super) {
    __extends(Wall, _super);

    function Wall() {
      return Wall.__super__.constructor.apply(this, arguments);
    }

    Wall.prototype.fcolor = '#222';

    Wall.prototype.bcolor = '#bbb';

    Wall.prototype.symbol = '#';

    return Wall;

  })(Tile);

  darken = function(color, amount) {
    var colorArray, darkened;
    colorArray = ROT.Color.fromString(color);
    darkened = ROT.Color.interpolate(colorArray, [0, 0, 0], amount);
    return ROT.Color.toHex(darkened);
  };

}).call(this);
