// Generated by CoffeeScript 1.7.1
(function() {
  ROT.Display.prototype.drawTextYCentered = function(y, text, maxWidth) {
    var x;
    x = Math.floor(this.getOptions().width / 2 - text.length / 2);
    return this.drawText(x, y, text, maxWidth);
  };

}).call(this);
