// Generated by CoffeeScript 1.7.1
(function() {
  this.WumpusDungeon = (function() {
    function WumpusDungeon() {}

    WumpusDungeon.prototype.create = function(callback) {
      return callback(0, 0);
    };

    return WumpusDungeon;

  })();

}).call(this);
