// Generated by CoffeeScript 1.7.1
(function() {
  this.WumpusDungeon = (function() {
    function WumpusDungeon(width, height) {
      this.width = width != null ? width : 32;
      this.height = height != null ? height : 32;
    }

    WumpusDungeon.prototype.create = function(callback) {
      var x, y, _i, _ref, _results;
      _results = [];
      for (x = _i = 0, _ref = this.width; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (y = _j = 0, _ref1 = this.height; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            _results1.push(callback(x, y));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return WumpusDungeon;

  })();

}).call(this);
