// Generated by CoffeeScript 1.7.1
(function() {
  describe('Map', function() {
    var map;
    map = new Map({});
    return describe('constructor', function() {
      var tileValues;
      tileValues = null;
      it('should have tiles property', function() {
        return map.should.have.property('tiles');
      });
      it('should have lots of tiles', function() {
        return map.tiles.keys().length.should.be.above(100);
      });
      it('should have floor tiles', function() {
        var c, hasFloor;
        tileValues = (function() {
          var _i, _len, _ref, _results;
          _ref = map.tiles.keys();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            c = _ref[_i];
            _results.push(map.tiles.get(c));
          }
          return _results;
        })();
        hasFloor = tileValues.some(function(element) {
          return element === '.';
        });
        return hasFloor.should.be.ok;
      });
      return it('should have wall tiles', function() {
        var hasWall;
        hasWall = tileValues.some(function(element) {
          return element === '#';
        });
        return hasWall.should.be["true"];
      });
    });
  });

}).call(this);
