// Generated by CoffeeScript 1.7.1
(function() {
  describe('Map', function() {
    return describe('Construction', function() {
      var map, tileValues;
      map = new Map({});
      tileValues = null;
      it('should have tiles property', function() {
        return map.should.have.property('tiles');
      });
      it('should have lots of tiles', function() {
        return Object.keys(map.tiles).length.should.be.above(100);
      });
      it('should have floor tiles', function() {
        var hasFloor, value, _;
        tileValues = (function() {
          var _ref, _results;
          _ref = map.tiles;
          _results = [];
          for (_ in _ref) {
            value = _ref[_];
            _results.push(value);
          }
          return _results;
        })();
        hasFloor = tileValues.some(function(element) {
          return element === '.';
        });
        return hasFloor.should.be.ok;
      });
      return it('should have wall tiles', function() {
        var hasWall;
        hasWall = tileValues.some(function(element) {
          return element === '#';
        });
        return hasWall.should.be.ok;
      });
    });
  });

}).call(this);
